---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: demo
  labels:
    app: chat
  annotations:
    fluxcd.io/automated: "true"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: chat
    spec:
      initContainers:
      - name: init
        image: alpine:20200626
        command:
        - sleep
        - "1"
      containers:
      - name: chat
        image: mrklar/my-feathers-image:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3030
          protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#999791"

