---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: demo
  labels:
    app: chat
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: glob:3.3.*
    fluxcd.io/tag.podinfod: glob:3.3.*
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: chat
    spec:
      initContainers:
      - name: init
        image: alpine:3.12
        command:
        - sleep
        - "1"
      containers:
      - name: chat
        image: my-feathers-image
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        command:
        - ./podinfo
        - --port=3030
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=chat
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: "#999791"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
